site_name: "Semantic SQL"
theme: readthedocs
nav:
  - Home: index.md
  - RDF: rdf_index.md
  - OWL: owl_index.md
  - OBO: obo_index.md
  - OMO: omo_index.md
site_url: https://cmungall.github.io/semantic-sql/
repo_url: https://github.com/cmungall/semantic-sql
