site_name: "Semantic SQL"
theme:
  name: readthedocs
  analytics:
    gtag: G-2SYBSJVZ23
nav:
  - Home: index.md
  - RDF: rdf_index.md
  - OWL: owl_index.md
  - OBO: obo_index.md
  - OMO: omo_index.md
  - Relation Graph: relation_graph_index.md
site_url: https://cmungall.github.io/semantic-sql/
repo_url: https://github.com/cmungall/semantic-sql
