#!/bin/sh

eval "$(conda shell.bash hook)"
conda activate semantic-sql
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
cd $SCRIPT_DIR/..
export PYTHONPATH="."
python3 -m semsql.subgraph "$@"
#pipenv run python -m semsql.subgraph "$@"
