name: Claude Issue Triage
description: "Automatically triage GitHub issues using Claude Code"

on:
  issues:
    types: [opened]

jobs:
  triage-issue:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          
      - name: Run Claude Issue Triage
        uses: ./.github/actions/claude-issue-triage-action
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          cborg_api_key: ${{ secrets.CBORG_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
